Add #ifdef BT_NO_SIMD_OPERATOR_OVERLOADS before including Bullet headers, to avoid clashes with XNAMath.h Fixes Issue 710 error C2084: function 'XMVECTOR operator +(FXMVECTOR,FXMVECTOR)' already has a body error C2084: function 'XMVECTOR operator -(FXMVECTOR,FXMVECTOR)' already has a body error C2084: function 'XMVECTOR operator *(FXMVECTOR,FXMVECTOR)' already has a body
git-svn-id: http://bullet.googlecode.com/svn@2659 08e121b0-ae19-0410-a57b-3be3395fd4fd